server:
  port: 5000

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: stluser
    password: Sgh@123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5InnoDBDialect




